List<Map<String, dynamic>> ticketList = [
  {
    'from': {'code': "NYC", 'name': "New-York"},
    'to': {'code': "LDN", 'name': "London"},
    'flying_time': '8H 30M',
    'date': "1 MAY",
    'departure_time': "08:00 AM",
    "number": 23,
  },
  {
    'from': {'code': "DK", 'name': "Dhaka"},
    'to': {'code': "SH", 'name': "Shanghai"},
    'flying_time': '4H 20M',
    'date': "10 MAY",
    'departure_time': "09:00 AM",
    "number": 45,
  },
  {
    'from': {'code': "SYD", 'name': "Sydney"},
    'to': {'code': "SIN", 'name': "Singapore"},
    'flying_time': '7H 15M',
    'date': "12 MAY",
    'departure_time': "10:30 AM",
    "number": 78,
  },
  {
    'from': {'code': "DXB", 'name': "Dubai"},
    'to': {'code': "IST", 'name': "Istanbul"},
    'flying_time': '4H 05M',
    'date': "14 MAY",
    'departure_time': "02:45 PM",
    "number": 91,
  },
  {
    'from': {'code': "BKK", 'name': "Bangkok"},
    'to': {'code': "HKG", 'name': "Hong Kong"},
    'flying_time': '2H 40M',
    'date': "16 MAY",
    'departure_time': "04:20 PM",
    "number": 56,
  },
  {
    'from': {'code': "FRA", 'name': "Frankfurt"},
    'to': {'code': "JFK", 'name': "New York"},
    'flying_time': '9H 10M',
    'date': "18 MAY",
    'departure_time': "06:15 PM",
    "number": 134,
  },
  {
    'from': {'code': "DEL", 'name': "Delhi"},
    'to': {'code': "KUL", 'name': "Kuala Lumpur"},
    'flying_time': '5H 25M',
    'date': "20 MAY",
    'departure_time': "11:00 AM",
    "number": 202,
  },
  {
    'from': {'code': "LAX", 'name': "Los Angeles"},
    'to': {'code': "TYO", 'name': "Tokyo"},
    'flying_time': '11H 30M',
    'date': "22 MAY",
    'departure_time': "01:50 PM",
    "number": 87,
  },
  {
    'from': {'code': "CPT", 'name': "Cape Town"},
    'to': {'code': "DXB", 'name': "Dubai"},
    'flying_time': '8H 55M',
    'date': "24 MAY",
    'departure_time': "08:40 AM",
    "number": 145,
  },
  {
    'from': {'code': "ROM", 'name': "Rome"},
    'to': {'code': "ATH", 'name': "Athens"},
    'flying_time': '1H 50M',
    'date': "26 MAY",
    'departure_time': "07:30 PM",
    "number": 99,
  },
];

List<Map<String, dynamic>> hotelList = [
  {
    'image': 'hotel_room_view_1.png',
    'place': 'Open Space',
    'destination': 'London',
    'price': 25,
  },
  {
    'image': 'hotel_room_view_2.png',
    'place': 'Global Will',
    'destination': 'London',
    'price': 40,
  },
  {
    'image': 'hotel_room_view_3.png',
    'place': 'Tallest Building',
    'destination': 'Dubai',
    'price': 68,
  },
];
